### PR TITLE
head function

### PR DESCRIPTION
**Pull request by domdere**
no more `rightToMaybe`, `listToMaybe`, `maybeToMaybe` etc....

### CODE REVIEW

**Comment by markhibberd** [comment]
:shaved_ice:

**Comment by domdere** [comment]
(just added a minor cosmetic correction https://github.com/ambiata/p/commit/c2569ccabe8cbe26b17a39cdd6579c59be9eac57)

**Comment by tmcgilchrist** [comment]
great addition :rocket:

**Comment by etorreborre** [comment]
Great. @domdere would it be useful to implement `last` as well?

**Comment by domdere** [comment]
@etorreborre not sure tbh, dont know how common that use case is. but i think @markhibberd  would argue that if `last` was being used frequently enough to warrant its existence, then its a smell that we arent using the right data structure (for e.g we should be using a snoc list maybe)

but i think we can get rid of `leftToMaybe` and its ilk if `bifunctors` is added to `p` and we compose `head` with [`Clown`] (https://hackage.haskell.org/package/bifunctors-3.2.0.1/docs/Data-Bifunctor-Clown.html). Again don't want to bother with it unless there are more use cases for it other than `Either`

**Comment by markhibberd** [comment]
@domdere We added a dependency on `either` last week, so `p` already depends on bifunctors, just need to re-export things if you want.

**Pull request merged**
