### PR TITLE
Support GHC 7.10.*, fix sdist

### PR DESCRIPTION
**Pull request by thumphries**
- `Data.List.sortOn` is in base now, so hide it until we drop 7.8 support
- Rename cabal file to fix `cabal sdist` (and hopefully stack), i.e. should this sequence should succeed

```
$ cabal sdist
$ cabal install dist/*.tar.gz
```

cc ambiata/yak#63

### CODE REVIEW

**Comment by thumphries** [comment]
That commit is poorly named, I should probably add a `stack.yaml` or reword it

**Comment by thumphries** [comment]
Also missed some AMP stuff, one sec...

**Comment by tranma** [comment]
does this currently build on 7.10? You could add a travis 7.10 build if you want, as this is public

**Comment by thumphries** [comment]
Builds with -Werror in 7.8.4 and 7.10.2 for me, I'll figure out some Travis now.

**Comment by tranma** [comment]
here's an existing one https://github.com/ambiata/icicle/blob/master/.travis.yml

**Comment by thumphries** [comment]
Build should pass now. Mafia hash needs to be bumped before this is mergeable, so blocked by ambiata/mafia#23

**Comment by jystic** [comment]
I think the cabal file should still be called `p.cabal` (even though the package name is `ambiata-p`)

Other than that :+1:

**Comment by markhibberd** [comment]
:+1:

**Comment by thumphries** [comment]
As IRL'd, renaming cabal files to fix sdist + stack. Travis job tests for this

**Pull request merged**
