### PR TITLE
Strict (call-by-value) function application operator ($!)

### PR DESCRIPTION
**Pull request by jystic**
It takes a function and an argument, evaluates the argument to weak head normal form (WHNF), then calls the function with that value.

```haskell
($!) :: (a -> b) -> a -> b
f $! x =
  let !vx = x in f vx
```

### CODE REVIEW

**Comment by tmcgilchrist** [comment]
:heart: 

Wasn't sure if there was a reason it was left out.

**Comment by nhibberd** [comment]
:100:

**Comment by markhibberd** [comment]
Related - https://github.com/ambiata/p/issues/53 - are there others?

**Comment by jystic** [comment]
Yeah there is `<$!>` in `Control.Monad` as of 7.10

**Pull request merged**
