### PR TITLE
Concrete composition

### PR DESCRIPTION
**Pull request by thumphries**
I really like to use `(...) = (.) . (.)` in anger, it seemed general enough to live in P.

I  don't know if this is useful to others or if it's ok to squat this namespace, just a proposal!

! @jystic @nhibberd @markhibberd @charleso

### CODE REVIEW

**Comment by charleso** [comment]
I'm obtaining from this. I don't have a problem with this, but at the same time I don't think I would use it.

**Comment by HuwCampbell** [comment]
Might want to consider inline pragmas as well.

**Comment by thumphries** [comment]
I only really want `(...)`, operators are spooky.

**Comment by erikd-ambiata** [comment]
@thumphries, on your `(...)` operator, you do want a `{-# INLINE (...) #-}` pragma. Thats what @HuwCampbell was getting at.

**Comment by jystic** [comment]
> I really like to use `(...) = (.) . (.)` in anger

Have you been using it? I'm weary of adding stuff to P before they've been proven useful is all - once something is in P it's unlikely that it'll get removed.

**Comment by thumphries** [comment]
> Have you been using it?

I usually spend 20 seconds adding a lambda when it happens (when I've changed the arity of something and ruined a pointfree expression)

Y'all sound suspicious though, happy to close

**Comment by jystic** [comment]
> Y'all sound suspicious though, happy to close

I'm just allergic to adding functionality directly to shared libraries before they've shown value in a downstream project, I've seen too many "common" libraries turn in to sewers this way.

I think there's nothing wrong with having a util module or something in a specific project where you can try something out before it gets promoted.

**Comment by jystic** [comment]
Happy to be convinced otherwise though :)

**Comment by thumphries** [comment]
`x-composr`, too large for github to display

**Pull request closed without merging**
