### PR TITLE
Export Bitraversable functions which were moved out from the class in 5.x

### PR DESCRIPTION
**Pull request by charleso**
! @olorin @jystic 

http://hackage.haskell.org/package/bifunctors-4.2.1/docs/Data-Bitraversable.html#v:bisequence

http://hackage.haskell.org/package/bifunctors-5.4.1/docs/Data-Bitraversable.html#v:bisequence

### CODE REVIEW

**Comment by charleso** [comment]
I'm hoping/assuming there won't be a compiler warning if the function imported twice in 4.x, but let me know if I'm wrong?

**Comment by olorin** [comment]
Sounds fine to me, :+1: on :green_apple:.

**Comment by charleso** [comment]
As discussed with @jystic they're the same functions as `bisequenceA`, will just use that instead

**Comment by jystic** [comment]
Was maybe more important in 7.8.4, but given we have `Applicative m => Monad m` it's all same/same now.

**Pull request closed without merging**
